// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViaEventAssociation.Infrastructure.EfcDmPersistence;

#nullable disable

namespace ViaEventAssociation.Infrastructure.EfcDmPersistence.Migrations
{
    [DbContext(typeof(DmContext))]
    partial class DmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ViaEventAssociation.Core.Domain.Aggregates.EventAggregate.EventAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxNumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Status", "ViaEventAssociation.Core.Domain.Aggregates.EventAggregate.EventAggregate.Status#EventStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Status");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Visibility", "ViaEventAssociation.Core.Domain.Aggregates.EventAggregate.EventAggregate.Visibility#EventVisibility", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Visibility");
                        });

                    b.HasKey("Id");

                    b.ToTable("EventAggregates");
                });

            modelBuilder.Entity("ViaEventAssociation.Core.Domain.Aggregates.EventAggregate.EventAggregate", b =>
                {
                    b.OwnsOne("ViaEventAssociation.Core.Domain.Aggregates.EventAggregate.Values.TimeInterval", "TimeInterval", b1 =>
                        {
                            b1.Property<Guid>("EventAggregateId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("EndDateTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("EndDateTime");

                            b1.Property<DateTime>("StartDateTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("StartDateTime");

                            b1.HasKey("EventAggregateId");

                            b1.ToTable("EventAggregates");

                            b1.WithOwner()
                                .HasForeignKey("EventAggregateId");
                        });

                    b.Navigation("TimeInterval");
                });
#pragma warning restore 612, 618
        }
    }
}
